name: HerokuContainer
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Create symbolic link DockerFile
        run: cp "AivenEcommerce.V1.WebApi/Dockerfile" "Dockerfile"
        
      - name: Deploy Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: aivenecommercev1apidemo
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
