name: HerokuContainer
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Create symbolic link DockerFile
        run: cp "AivenEcommerce.V1.WebApi/Dockerfile" "Dockerfile"
        
      - name: Set Mongo Product ConnectionString JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          field: "MongoProductOptions.ConnectionString"
          value: ${{ secrets.MONGO_PRODUCT_CONNECTION_STRING }}

      - name: Set Mongo Order ConnectionString JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          field: "MongoOrderOptions.ConnectionString"
          value: ${{ secrets.MONGO_ORDER_CONNECTION_STRING }}

      - name: Set Mongo Sale ConnectionString JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          field: "MongoSaleOptions.ConnectionString"
          value: ${{ secrets.MONGO_Sale_CONNECTION_STRING }}
          
      - name: Set ImgBB ApiKey JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          field: "ImgBbOptions.ApiKey"
          value: ${{ secrets.IMGBB_API_KEY }}
          
      - name: Set GitHub Token JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          field: "GitHubOptions.Token"
          value: ${{ secrets.GH_TOKEN }}
         
      - name: Upload AppSettings 
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: AivenEcommerce.V1.WebApi/appsettings.json
    
    
      - name: Deploy Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: aivenecommercev1apidemo
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
