name: HerokuContainer
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Create symbolic link DockerFile
        run: cp "AivenEcommerce.V1.WebApi/Dockerfile" "Dockerfile"
        
      - name: Set Mongo Product ConnectionString JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          # file name/path to edit. e.g 'package.json'
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          # field to edit. can be nested fields. e.g 'version' or 'metadata.scripts.build'
          field: "MongoProductOptions.ConnectionString"
          # value to set. string. e.g. 'v1.2.3'
          value: ${{ secrets.MONGO_PRODUCT_CONNECTION_STRING }}

      - name: Set Mongo Order ConnectionString JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          # file name/path to edit. e.g 'package.json'
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          # field to edit. can be nested fields. e.g 'version' or 'metadata.scripts.build'
          field: "MongoOrderOptions.ConnectionString"
          # value to set. string. e.g. 'v1.2.3'
          value: ${{ secrets.MONGO_ORDER_CONNECTION_STRING }}
          
      - name: Set ImgBB ApiKey JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          # file name/path to edit. e.g 'package.json'
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          # field to edit. can be nested fields. e.g 'version' or 'metadata.scripts.build'
          field: "ImgBbOptions.ApiKey"
          # value to set. string. e.g. 'v1.2.3'
          value: ${{ secrets.IMGBB_API_KEY }}
          
      - name: Set GitHub Token JSON Field
        uses: jossef/action-set-json-field@v1
        with:
          # file name/path to edit. e.g 'package.json'
          file: "AivenEcommerce.V1.WebApi/appsettings.json"
          # field to edit. can be nested fields. e.g 'version' or 'metadata.scripts.build'
          field: "GitHubOptions.Token"
          # value to set. string. e.g. 'v1.2.3'
          value: ${{ secrets.GH_TOKEN }}
        
      - name: Deploy Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: aivenecommercev1apidemo
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
