name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        fetch-depth: 100 # avoid shallow clone so nbgv can do its work.
        
        
    - uses: marceloprado/has-changed-path@v1
      id: changed-domain-shared
      with:
        paths: AivenEcommerce.V1.Domain.Shared
        
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
        
    - name: Deploy Pack
      run: dotnet build AivenEcommerce.V1.Domain.Shared/AivenEcommerce.V1.Domain.Shared.csproj --configuration Release
      
    - name: Install gpr
      if: steps.changed-domain-shared.outputs.changed == 'true'
      run: dotnet tool install gpr --global
    
    - name: gpr upload
      if: steps.changed-domain-shared.outputs.changed == 'true'
      run: find -name "*.nupkg" -print -exec gpr push -k ${{secrets.GH_PACKAGE}} {} \;
      
    - name: Update Nuget
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  'AivenEcommerce.V1.Domain.Shared/bin/Release/*.nupkg'
        repo-owner:  'aivenweb'
        gh-user:  'aivenweb'
        token:  ${{ secrets.GH_AIVEN_TOKEN }}
