name: Tests Coverage
 
on:
  push:
    branches:
      - main
 
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup .NET 5.0.100
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.100'

      - name: Recommpilar Datos Coverlet
        run: dotnet test --collect:"XPlat Code Coverage"
        working-directory: AivenEcommerce.V1.Application.Tests

      - name: Save Guid TestResults Coverage
        run: echo "COVERAGE_GUID=$(ls)" >> $GITHUB_ENV
        working-directory: AivenEcommerce.V1.Application.Tests/TestResults

      - name: View Guid
        run: echo ${{ env.COVERAGE_GUID }}

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Report
        run: reportgenerator "-reports:TestResults/${{ env.COVERAGE_GUID }}/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
        working-directory: AivenEcommerce.V1.Application.Tests


      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          TARGET_FOLDER: TestCoverage
          FOLDER: AivenEcommerce.V1.Application.Tests/coveragereport
          CLEAN: true 

      
      
